

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems: [jekyll-paginate]

# Site settings
title: "Restful Brilliance LLC"
email: rstrube@restfulbrilliance.com
description: > # this means to ignore newlines until "baseurl:"
  Restful Brilliance LLC, web development, API development, eCommerce web sites, EPiServer, Shopify, Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://restfulbrilliance.com" # the base hostname & protocol for your site
twitter_username: restbrilliance
github_username: rstrube
permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 2
paginate_path: /blog/page:num/

# Build settings
markdown: kramdown

# This tells Jekyll to ignore (i.e. do not copy and/or compile to the _site directory) the following:
# 1. NPM packages and the configuration file (package.json)
# 2. Bower components and the configuration file (bower.json)
# 3. Gulp configuration file (gulpfile.js)
# 4. css directory
# 5. _sass directory
# 6. js directory
# 7. Visual Studio Solution File (*.sln)
# Note: we're excluding the css, _sass, and js directories because we're letting Gulp do the sass -> css compilation and the js concatenation, not Jekyll

exclude: ['node_modules',
		  'package.json',
		  'bower_components',
		  'bower.json',
		  'gulpfile.js',
		  'css',
		  '_sass',
		  'js',
		  'RB.sln']

# This tells Jekyll to keep the Gulp generated CSS and JS in the _site directory
keep_files: ['_site/css',
			 '_site/js']

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Robert Strube"
      author_bio: "Robert Strube is the founder of RB.  He loves anything having to do with web development and security.  He also enjoys road cycling, hiking, skiing, motorcycles, and sailing."
      author_img: "/img/author/default.png"
      author_github: "rstrube"
      author_facebook:
      author_linkedin:
      author_twitter: "rdstrube"